### PR TITLE
Add a example using stop_sequences

### PR DESCRIPTION
**Pull request by MarkDaoust**
and regenerate outputs.

b/283100526

### CODE REVIEW

**Comment by pcoet** [comment]
Is there a simple way to review this PR in Colab, or do you have to just look at the raw notebook file? I can probably answer my own question -- just being hopeful. :-)

**Comment by MarkDaoust** [comment]
Let me see if i can hook up ReviewNB, one second.

**Comment by MarkDaoust** [comment]
Okay, Review NB is set for the repo. But It looks like I broke the notebook...

**Comment by MarkDaoust** [comment]
Fixed:  https://app.reviewnb.com/google/generative-ai-docs/pull/26/

**Review by pcoet — APPROVED** [review]
This is my first time seeing the `palm` API, but the new code example -- LGTM.

**Pull request merged**
