### PR TITLE
[Release] Docs Agent version 0.2.1

### PR DESCRIPTION
**Pull request by kyolee415**
## Description of the change
- Integrate the Semantic Retrieval API and AQA model to Docs Agent.
- Turn `chroma.py` and `palm.py` into modules.
- Refactor and enhance the pre-processing scripts.
- Introduce `files_to_plain_text.py`, which will replace `markdown_to_plain_text.py`.
- Add a new doc: `doc/whats-new.md`

## Motivation
New features added to Docs Agent 0.2.1.

## Type of change
Choose one: (Feature request)

## Checklist

- [ X] I have performed a self-review of my code.
- [ X] I have added detailed comments to my code where applicable.
- [ X] I have verified that my change does not break existing code.
- [ X] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ X] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [ X] I have read through the [Contributing Guide](https://github.com/google/generative-ai-docs/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).

### CODE REVIEW

**Review by nickvander — APPROVED** [review]
LGTM!

**Comment by kyolee415** [comment]
Verified that the setup instructions documented on README.md worked with the changes in this PR.

**Comment by markmcd** [comment]
You need me for anything here?

**Comment by kyolee415** [comment]
It looks like @nickvander has already LGTM'ed this PR. I'll go ahead and merge this PR then. Thanks!

**Pull request merged**
