### PR TITLE
Update distributed_tuning.ipynb

### PR DESCRIPTION
**Pull request by windmaple**
Link to Colab tutorial for Gemma distributed finetuning

## Description of the change

Originally Colab didn't work for Gemma dist finetuning. But Colab team figured it out and created a copy of the tutorial that works on Colab TPU.

### CODE REVIEW

**Review by pcoet — APPROVED** [review]

**Comment by pcoet** [comment]
The linter is complaining about the Colab link. It might be a false positive, but we should update the link to not use the Colab sandbox (`colab.sandbox.google.com`).

**Comment by windmaple** [comment]
Fixed

**Review by pcoet — APPROVED** [review]

**Comment by pcoet** [comment]
Thanks. It looks like the notebook on GitHub is not the same one we're opening in Colab, but I'm sure that's for a reason. I'll squash/merge.

**Comment by windmaple** [comment]
Right. Colab team had to fork it to do some hacking due to its lower version of TPU v2. Kaggle offers TPU v3.

**Pull request merged**
